# Runs tests and builds the source

name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  Test:
  - uses: actions/checkout@v2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
      - run: yarn install --frozen-lockfile
      - run: yarn lint

      - name: Run tests with Node.js ${{ matrix.node-version }}
      - run: yarn test

  Build:
    needs: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build with Node.js ${{ matrix.node-version }}
      - run: yarn build
